spring:
  application:
    name: 10-security
  datasource:
    url: jdbc:sqlite:10-security/src/main/resources/db/10.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
  redis:
    host: localhost
    port: 6379
    database: 1
server:
  port: 8010
mybatis:
  mapper-locations: classpath:mappers/**/*.xml