spring:
  application:
    name: 25-security
  datasource:
    url: jdbc:sqlite:25-security/src/main/resources/db/25.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
  redis:
    host: localhost
    port: 6379
    database: 4
server:
  port: 8025
mybatis:
  mapper-locations: classpath:mappers/**/*.xml