spring:
  application:
    name: 14-security
  datasource:
    url: jdbc:sqlite:14-security/src/main/resources/db/14.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
server:
  port: 8014
mybatis:
  mapper-locations: classpath:mappers/**/*.xml