spring:
  application:
    name: 26-security
  datasource:
    url: jdbc:sqlite:26-security/src/main/resources/db/26.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
  redis:
    host: localhost
    port: 6379
    database: 4
server:
  port: 8026
mybatis:
  mapper-locations: classpath:mappers/**/*.xml

