spring:
  application:
    name: 08-security
  datasource:
    url: jdbc:sqlite:08-security/src/main/resources/db/08.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
server:
  port: 8008
mybatis:
  mapper-locations: classpath:mappers/**/*.xml