spring:
  application:
    name: 21-security
  datasource:
    url: jdbc:sqlite:21-security/src/main/resources/db/21.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
server:
  port: 8021
mybatis:
  mapper-locations: classpath:mappers/**/*.xml