spring:
  application:
    name: 11-security
  datasource:
    url: jdbc:sqlite:11-security/src/main/resources/db/11.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
server:
  port: 8011
mybatis:
  mapper-locations: classpath:mappers/**/*.xml