spring:
  application:
    name: 112-security
  datasource:
    url: jdbc:sqlite:11-security-2/src/main/resources/db/112.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
server:
  port: 8211
mybatis:
  mapper-locations: classpath:mappers/**/*.xml