spring:
  application:
    name: 29-security
  datasource:
    url: jdbc:sqlite:29-security/src/main/resources/db/29.db
    password:
    username:
    driver-class-name: org.sqlite.JDBC
  redis:
    host: localhost
    port: 6379
    database: 4
server:
  port: 8029
mybatis:
  mapper-locations: classpath:mappers/**/*.xml

